import Header from "./Header"
import Footer from "./Footer"
import Head from "next/head"

interface Props {
  children: React.ReactNode
}

export default function Layout({ children }: Props) {
    return (
        <>
            <Head>
                <title>GUCEM</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>{children}</main>
            <Footer />
        </>
    )}
